- de/subset/pin_taskbar_fox_doodle_2023.ftl
- en-US/subset/pin_taskbar_fox_doodle_2023.ftl
- fr/subset/pin_taskbar_fox_doodle_2023.ftl
- l10n.toml
> Add files and existing translations for Fox Doodle experiment

- .github/scripts/import_experiment.py
- If the `$l10n` match is not an object
- If the `$l10n` match is missing a `id` or `text` attributes
> Show more warnings for errors in recipe

- .github/storage/experiments.json
- de/subset/fox_doodle_set_to_default_early_day_graphics_2023.ftl
- en-CA/subset/fox_doodle_set_to_default_early_day_graphics_2023.ftl
- en-GB/subset/fox_doodle_set_to_default_early_day_graphics_2023.ftl
- en-US/subset/fox_doodle_set_to_default_early_day_graphics_2023.ftl
- fr/subset/fox_doodle_set_to_default_early_day_graphics_2023.ftl
- l10n.toml
See issue https://github.com/mozilla-l10n/nimbus-l10n/issues/15
> Set up localization for experiment fox-doodle-set-to-default-early-day-graphics

- .github/storage/experiments.json
- de/subset/fox_doodle_pin_to_taskbar_early_day_graphics_2023.ftl
- en-CA/subset/fox_doodle_pin_to_taskbar_early_day_graphics_2023.ftl
- en-GB/subset/fox_doodle_pin_to_taskbar_early_day_graphics_2023.ftl
- en-US/subset/fox_doodle_pin_to_taskbar_early_day_graphics_2023.ftl
- fr/subset/fox_doodle_pin_to_taskbar_early_day_graphics_2023.ftl
- l10n.toml
See issue https://github.com/mozilla-l10n/nimbus-l10n/issues/16
> Set up localization for experiment fox-doodle-pin-to-taskbar-early-day-graphics

- .github/storage/experiments.json
- en-CA/subset/backgroundtaskmessage_pip_notification_2023.ftl
- en-US/subset/backgroundtaskmessage_pip_notification_2023.ftl
- l10n.toml
See issue https://github.com/mozilla-l10n/nimbus-l10n/issues/19
> Set up localization for experiment backgroundtaskmessage-pip-notification

- .github/storage/experiments.json
- en-US/subset/new_user_test_copy_about_privacy_speed_security_fx120_2023.ftl
- l10n.toml
See issue https://github.com/mozilla-l10n/nimbus-l10n/issues/21
> Set up localization for experiment new-user-test-copy-about-privacy-speed-security-fx120

- .github/storage/experiments.json
- en-CA/subset/new_tab_microsurvey_relevance_satisfaction_2024.ftl
- en-GB/subset/new_tab_microsurvey_relevance_satisfaction_2024.ftl
- en-US/subset/new_tab_microsurvey_relevance_satisfaction_2024.ftl
- l10n.toml
See issue https://github.com/mozilla-l10n/nimbus-l10n/issues/25
> Set up localization for experiment new-tab-microsurvey-relevance-satisfaction

- .github/storage/experiments.json
- en-CA/subset/ask_windows_mac_desktop_early_day_profiles_about_their_firefox_use_case_2024.ftl
- en-GB/subset/ask_windows_mac_desktop_early_day_profiles_about_their_firefox_use_case_2024.ftl
- en-US/subset/ask_windows_mac_desktop_early_day_profiles_about_their_firefox_use_case_2024.ftl
- l10n.toml
See issue https://github.com/mozilla-l10n/nimbus-l10n/issues/27
> Set up localization for experiment ask-windows-mac-desktop-early-day-profiles-about-their-firefox-use-case

- .github/storage/experiments.json
- en-US/subset/discovery_of_search_sap_existing_it_de_fr_2024.ftl
- l10n.toml
See issue https://github.com/mozilla-l10n/nimbus-l10n/issues/29
> Set up localization for experiment discovery-of-search-sap-existing-it-de-fr

- .github/storage/experiments.json
- en-CA/subset/pdf_annotations_highlight_already_default_handler_2024.ftl
- en-GB/subset/pdf_annotations_highlight_already_default_handler_2024.ftl
- en-US/subset/pdf_annotations_highlight_already_default_handler_2024.ftl
- l10n.toml
See issue https://github.com/mozilla-l10n/nimbus-l10n/issues/36
> Set up localization for experiment pdf-annotations-highlight-already-default-handler

- .github/storage/experiments.json
- en-CA/subset/microsurvey_sync_csat_2024_2024.ftl
- en-GB/subset/microsurvey_sync_csat_2024_2024.ftl
- en-US/subset/microsurvey_sync_csat_2024_2024.ftl
- l10n.toml
See issue https://github.com/mozilla-l10n/nimbus-l10n/issues/38
> Set up localization for experiment microsurvey-sync-csat-2024

- .github/storage/experiments.json
- en-CA/subset/recommend_bookmark_toolbar_existing_user_2024.ftl
- en-GB/subset/recommend_bookmark_toolbar_existing_user_2024.ftl
- en-US/subset/recommend_bookmark_toolbar_existing_user_2024.ftl
- l10n.toml
See issue https://github.com/mozilla-l10n/nimbus-l10n/issues/42
> Set up localization for experiment recommend-bookmark-toolbar-existing-user

- .github/storage/experiments.json
- en-CA/subset/fox_doodle_multi_action_cta_fr_it_de_2024.ftl
- en-GB/subset/fox_doodle_multi_action_cta_fr_it_de_2024.ftl
- en-US/subset/fox_doodle_multi_action_cta_fr_it_de_2024.ftl
- l10n.toml
See issue https://github.com/mozilla-l10n/nimbus-l10n/issues/47
> Set up localization for experiment fox-doodle-multi-action-cta-fr-it-de

- .github/storage/experiments.json
- en-CA/subset/microsurvey_addons_csat_2024_2024.ftl
- en-GB/subset/microsurvey_addons_csat_2024_2024.ftl
- en-US/subset/microsurvey_addons_csat_2024_2024.ftl
- l10n.toml
See issue https://github.com/mozilla-l10n/nimbus-l10n/issues/53
> Set up localization for experiment microsurvey-addons-csat-2024

- .github/storage/experiments.json
- en-CA/subset/npo_sign_up_sign_in_button_text_change_2024.ftl
- en-GB/subset/npo_sign_up_sign_in_button_text_change_2024.ftl
- en-US/subset/npo_sign_up_sign_in_button_text_change_2024.ftl
- l10n.toml
See issue https://github.com/mozilla-l10n/nimbus-l10n/issues/55
> Set up localization for experiment npo-sign-up-sign-in-button-text-change

- .github/storage/experiments.json
- de/subset/pdf_annotations_signatures_ab_experiment_2025.ftl
- en-CA/subset/pdf_annotations_signatures_ab_experiment_2025.ftl
- en-GB/subset/pdf_annotations_signatures_ab_experiment_2025.ftl
- en-US/subset/pdf_annotations_signatures_ab_experiment_2025.ftl
- fr/subset/pdf_annotations_signatures_ab_experiment_2025.ftl
- it/subset/pdf_annotations_signatures_ab_experiment_2025.ftl
- l10n.toml
See issue https://github.com/mozilla-l10n/nimbus-l10n/issues/61
> Set up localization for experiment pdf-annotations-signatures-ab-experiment

- .github/storage/experiments.json
- en-CA/subset/account_adoption_callout_passwords_2025.ftl
- en-GB/subset/account_adoption_callout_passwords_2025.ftl
- en-US/subset/account_adoption_callout_passwords_2025.ftl
- l10n.toml
See issue https://github.com/mozilla-l10n/nimbus-l10n/issues/63
> Set up localization for experiment account-adoption-callout-passwords

- .github/storage/experiments.json
- en-CA/subset/tab_groups_user_satisfaction_microsurvey_2025.ftl
- en-GB/subset/tab_groups_user_satisfaction_microsurvey_2025.ftl
- en-US/subset/tab_groups_user_satisfaction_microsurvey_2025.ftl
- l10n.toml
See issue https://github.com/mozilla-l10n/nimbus-l10n/issues/65
> Set up localization for experiment tab-groups-user-satisfaction-microsurvey

- .github/storage/experiments.json
- en-CA/subset/account_adoption_callout_credit_cards_and_addresses_2025.ftl
- en-GB/subset/account_adoption_callout_credit_cards_and_addresses_2025.ftl
- en-US/subset/account_adoption_callout_credit_cards_and_addresses_2025.ftl
- l10n.toml
See issue https://github.com/mozilla-l10n/nimbus-l10n/issues/67
> Set up localization for experiment account-adoption-callout-credit-cards-and-addresses

- .github/storage/experiments.json
- en-CA/subset/temp_copy_of_account_adoption_callout_for_l10n_re_extraction_2025.ftl
- en-GB/subset/temp_copy_of_account_adoption_callout_for_l10n_re_extraction_2025.ftl
- en-US/subset/temp_copy_of_account_adoption_callout_for_l10n_re_extraction_2025.ftl
- l10n.toml
See issue https://github.com/mozilla-l10n/nimbus-l10n/issues/69
> Set up localization for experiment temp-copy-of-account-adoption-callout-for-l10n-re-extraction

- .github/storage/experiments.json
- de/subset/account_adoption_callout_credit_cards_and_addresses_corrected_copy_2025
- en-CA/subset/account_adoption_callout_credit_cards_and_addresses_corrected_copy_2025.ftl
- en-GB/subset/account_adoption_callout_credit_cards_and_addresses_corrected_copy_2025.ftl
- en-US/subset/account_adoption_callout_credit_cards_and_addresses_corrected_copy_2025.ftl
- fr/subset/account_adoption_callout_credit_cards_and_addresses_corrected_copy_2025
- it/subset/account_adoption_callout_credit_cards_and_addresses_corrected_copy_2025
- l10n.toml
See issue https://github.com/mozilla-l10n/nimbus-l10n/issues/71
> Set up localization for experiment account-adoption-callout-credit-cards-and-addresses-corrected-copy

- en-CA/subset/windows_10_end_of_service_sync_messages_2025.ftl
- en-GB/subset/windows_10_end_of_service_sync_messages_2025.ftl
- en-US/subset/windows_10_end_of_service_sync_messages_2025.ftl
- l10n.toml
> Manually create nimbus experiment for windows 10 end of service sync messages

- .github/storage/experiments.json
- en-CA/subset/account_adoption_callout_bookmarks_2025.ftl
- en-GB/subset/account_adoption_callout_bookmarks_2025.ftl
- en-US/subset/account_adoption_callout_bookmarks_2025.ftl
- l10n.toml
See issue https://github.com/mozilla-l10n/nimbus-l10n/issues/76
> Set up localization for experiment account-adoption-callout-bookmarks

- .github/storage/experiments.json
- en-CA/subset/address_bar_tips_2025.ftl
- en-GB/subset/address_bar_tips_2025.ftl
- en-US/subset/address_bar_tips_2025.ftl
- l10n.toml
See issue https://github.com/mozilla-l10n/nimbus-l10n/issues/81
> Set up localization for experiment address-bar-tips
